services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: smart_exam_backend_image
    container_name: smart_exam_backend_container
    env_file:
      - ./backend/.env
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: smart_exam_frontend_nginx_image
    container_name: smart_exam_frontend_nginx
    env_file:
      - ./frontend/.env
      - ./frontend/nginx/.env
    networks:
      - app_network
    ports:
      - "80:80"

networks:
  app_network:
    driver: bridge
